apiVersion: v1
kind: Service
metadata:
  name: app-svc
  labels:
    app: app-svc
spec:
  type: LoadBalancer
  selector:
    app: app-weather
  ports:
    - name: http
      protocol: TCP
      port: 80             # Public port exposed via LoadBalancer
      targetPort: 5000     # Internal Flask app port
