name: demo-workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.get_tag.outputs.image_tag }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Image
        id: get_tag
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          IMAGE_NAME=docker.io/${{ secrets.DOCKER_USERNAME }}/weather-app:$IMAGE_TAG
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to GKE
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update image tag in deployment.yaml
        run: |
          sed -i "s|image: .*|image: docker.io/${{ secrets.DOCKER_USERNAME }}/weather-app:${{ needs.build.outputs.image_tag }}|g" app-k8s/deployment.yaml

      - name: Install gcloud CLI & gke-gcloud-auth-plugin
        run: |
          curl -sSL https://dl.google.com/cloudsdk/channels/rapid/downloads/google-cloud-cli-464.0.0-linux-x86_64.tar.gz -o gcloud.tar.gz
          tar -xf gcloud.tar.gz
          ./google-cloud-sdk/install.sh -q
          echo "$PWD/google-cloud-sdk/bin" >> $GITHUB_PATH
          ./google-cloud-sdk/bin/gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Authenticate to GCP using service account
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 -d > "${{ github.workspace }}/gcloud-key.json"
          gcloud auth activate-service-account --key-file="${{ github.workspace }}/gcloud-key.json"
          gcloud config set project fluent-aileron-460117-t4
          gcloud container clusters get-credentials flask-k8s --region us-central1

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy to GKE
        run: |
          kubectl apply -f app-k8s/deployment.yaml
          kubectl apply -f app-k8s/service.yaml
          kubectl rollout status deployment/app-weather
